development:
  smtp_settings:         
    address:               smtp.gmail.com 
    port:                  587
    domain:                www.9mmedia.com
    user_name:             '$GMAIL_USERNAME'
    password:              '$GMAIL_PASSWORD'
    authentication:        plain
    enable_starttls_auto:  true

  send_emails: true

  ssl_required: false


test:
  smtp_settings:         
    address:               smtp.gmail.com 
    port:                  587
    domain:                www.9mmedia.com
    user_name:             '$GMAIL_USERNAME'
    password:              '$GMAIL_PASSWORD'
    authentication:        plain
    enable_starttls_auto:  true

  send_emails: false

  ssl_required: false


production:
  smtp_settings:         
    address:               smtp.gmail.com 
    port:                  587
    domain:                www.9mmedia.com
    user_name:             '$GMAIL_USERNAME'
    password:              '$GMAIL_PASSWORD'
    authentication:        plain
    enable_starttls_auto:  true

  send_emails: true

  ssl_required: false